### ISSUE TITLE
Help in finding firmware please

### ISSUE THREAD

**Issue by BohdanGut** [Koenkk/zigbee-OTA#119]
i have tuya kt series 1 and 2 gang switches.  

[https://pl.aliexpress.com/item/1005001470427730.html?spm=a2g0o.productlist.0.0.15e81634p8zkPw&algo_pvid=b0feda78-1db9-46af-b077-9eadf6993a13&algo_exp_id=b0feda78-1db9-46af-b077-9eadf6993a13-20&pdp_ext_f=%7B%22sku_id%22%3A%2212000016290125532%22%7D&pdp_npi=2%40dis%21PLN%21%21109.41%21%21%21%21%21%402100bdf116526178801687505e449d%2112000016290125532%21sea](url)

where can i find firmware update for it? it reports as 
 '_TZ3000_gbshwgag TS0001': field_control=FieldControl.0, manufacture_id=4098, image_type=5634, current_file_version=71, hardware_version=None, model=TS0001

in index.json i found 2 images that have image_id and manufecturer id thesame as above. but ZHA wont update. Can any 1 help?

**Comment by owangen** [comment]
Hi. This https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html#get-tuya-and-xiaomi-ota-url is the only way to find out afaik.
