### ISSUE TITLE
Error while trying to update Sonoff ZBMini-L (Value for field "payload_type" is requierd)

### ISSUE THREAD

**Issue by Fenx2310** [Koenkk/zigbee-OTA#136]
So i tried to update my ZBmini-L devices with the new firmware because of some issues with them, but eevery time i tried i get the same error message as statet in the title.

Also if i tried to send any other Cluster Command it states that there are other Values in diffrent fields missing.

![image](https://user-images.githubusercontent.com/44621302/178100996-3141fb05-81e6-410a-a322-374a81685baa.png)
![image](https://user-images.githubusercontent.com/44621302/178101004-5b992346-30c4-4c7b-a643-faed2bb2c004.png)

i also included a picture of the error messages but its in german and from my Cluster Manage page wich i used to update these

i dont know if i have to write something in the "Hersteller-Code Überschreiben" field or not because the update side from sonoff dident state that.

https://sonoff.tech/product-review/local-configure-zigbee-ota-in-home-assistant-tutorial/

**Comment by Koenkk** [comment]
This is a ZHA issue, please create the issue in the ZHA issue tracker.
