### ISSUE TITLE
Tuya Smart Plug (20A) TS011F Image

### ISSUE THREAD

**Issue by V4n1X** [Koenkk/zigbee-OTA#144]
Here is a image I got that you can add:

Model: _TZ3000_cehuw1lw

https://images.tuyaeu.com/smart/firmware/upgrade/20220602/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin

Should fix the random power off issue and enhance connectivity.

**Comment by V4n1X** [comment]
Updated existing entry ({"fileVersion":77,"fileSize":307682,"manufacturerCode":4417,"imageType":54179,"sha512":"97ea8413e8ab662f2bebf3b013b3030754cbc2c0744b91b14741fff17a2d8d99e7088aa22a3b6e43b3595ccd65433f96d32516fc057fddcc13a816c921af8c97","url":"https://images.tuyaeu.com/smart/firmware/upgrade/20220602/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin"})

**Comment by cloudbr34k84** [comment]
> Here is a image I got that you can add:
> 
> Model: _TZ3000_cehuw1lw
> 
> https://images.tuyaeu.com/smart/firmware/upgrade/20220602/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin
> 
> Should fix the random power off issue and enhance connectivity.

Hey, how do you apply this as i have the TS011F
by _TZ3000_typdpbpg and maybe this might fix the issue if it just turning off??

**Comment by SgtBatten** [comment]
Did you make this @V4n1X 

How did you "get" it?
