### ISSUE TITLE
OTA Update LED1624G9 won't start

### ISSUE THREAD

**Issue by djusHa** [Koenkk/zigbee-OTA#167]
Hi,

failed with this Message
`2022-10-16 11:09:21Failed to check if update available for 'kizi_decke_lampe' (No image available for imageType '10241')`

Any hints?

**Comment by Koenkk** [comment]
This means IKEA doesn't have an OTA available for this device yet. (we use the official IKEA server).

**Comment by djusHa** [comment]
Oh, thanks for clarifying!
