### ISSUE TITLE
Zlinky : Wrong OTA

### ISSUE THREAD

**Issue by mospaeda** [Koenkk/zigbee-OTA#177]
Now version 11 / latest official and released
see https://github.com/fairecasoimeme/Zlinky_TIC/releases
Currently it is only version 5 in json file

**Comment by mdeweerd** [comment]
The problem with the Zlinky binary is that the author release a version which was not ok and labeled it as "pre-release" later.

Update #154 ->  Remove #156

Apparently somebody updated recently: #190

Also, there now is the rooter version and non router version.

So now v12 is released only 11 days ago and updated only 4 days later  - I do not know if it wise to update the version that fast given the history.
