### ISSUE TITLE
HUE 277

### ISSUE THREAD

**Issue by fnfid** [Koenkk/zigbee-OTA#2]
Seem to me the plugs and lamps share same firmware, 929002240401 (LOM001) is looking for firmware type 277 not recognized, the bulb 929001953301 (LTG002) is recognized, all having firmware 1.65.9_hB3217DF4, so maybe plugs just ignore the brightness/color commands and can easily be supported.

**Comment by Koenkk** [comment]
The firmware for `imageType` `277` is not available yet (didn't find it yet) (https://github.com/Koenkk/zigbee-OTA/blob/master/index.json).

Firmwares with a different `imageType` cannot be used for devices having another `imageType`. If you are able to find this firmware it can be added.
