### ISSUE TITLE
Eurotronic Technology Spirit Zigbee OTA provider source

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee-OTA#22]
FYI, EUROTRONIC Technology GmbH recently started publishing official OTA firmware image releases on GitHub:

https://github.com/EUROTRONIC-Technology/Spirit-ZigBee/releases

Released firmware image is for their "Spirit ZigBee" (model "SPZB0001") product which is TVR (Thermostatic Radiator Valve) device:

https://www.zigbee2mqtt.io/devices/SPZB0001.html

https://eurotronic.org/produkte/zigbee-heizkoerperthermostat/spirit-zigbee/

They have also posted guide on how to OTA update using deCONZ software from Dresden Elektronik:

https://github.com/EUROTRONIC-Technology/Spirit-ZigBee/wiki/OTA-update-guide-via-deCONZ

https://github.com/EUROTRONIC-Technology/Spirit-ZigBee/blob/main/README.md

PS: Apparently upgrading is recommended because issues like these https://github.com/search?q=%22spirit+zigbee%22&state=open&type=Issues

**Comment by Koenkk** [comment]
This firmware has already been added (https://github.com/Koenkk/zigbee-OTA/commit/53d2f6af9c93b384b1f4d98d6f6312f7312858ea)

**Comment by BeistleA** [comment]
Hey Koenkk,

sorry to bother you in this case. I got TVR´s with 20191014 FW and get the message that the FW on the device is newer than the one available.  Is there any possibility to downgrade them cause the new FW ist the faulty one.

Thanks in avantage
Andy

**Comment by h-tro** [comment]
Hi Koenkk,

I am using a **new** Eurotronic SPZB0001 with firmware 20191014 and  Zigbee2mqtt Current version: 1.18.1-2

![EurotronicSpiritZigBee](https://user-images.githubusercontent.com/33256321/111176888-03d29900-85aa-11eb-8c1d-f7609a9a4a4f.JPG)

**and I get the following error:**

_Zigbee2MQTT:error 2021-03-15 15:09:54: Failed to check if update available for 'EurotronicSP-01' (No image available for imageType '65535')_

Can you explain that ?

Thanks
HTro

**Comment by hargathor** [comment]
Same issue for me, "the firmware is newer than the latest firmware online". The faulty one beeing the new firmware is it possible to force a downgrade of the device ?

**Comment by IronButterfly** [comment]
Same story. Is it possible to force firmware downgrade for "SPZB0001"?
