### ISSUE TITLE
Can not find OTA image for Danfoss Ally TRV

### ISSUE THREAD

**Issue by gedemagt** [Koenkk/zigbee-OTA#265]
Hi,

I recently bought a Danfoss Ally TRV, which is nicely supported by Z2M, and there are OTA updates in this repo.
However, when I try to check for updates, it says that it could not find any images for imageType 288
![image](https://user-images.githubusercontent.com/2789746/221370868-8654dac4-0042-4694-adb9-303d45b79ad6.png)

I can see that in you index.json in this repo, the imageType for Danfoss is also 256. 

Can you help me with why this doesn't recognize the correct version and type? My device looks like this:
![image](https://user-images.githubusercontent.com/2789746/221370947-ad6effe1-18fe-426c-9a21-3030916da2a1.png)

**Comment by lasse-aagren** [comment]
I have same issue with newly bought ally's

**Comment by red-island** [comment]
As I do no permission to create a branch/pull request here the solution for the coders:

This is the new model from Danfoss Ally => there is a new image id 0x0120
Hence, index.json needs to get a new entry.

Copy record with "manufacturerCode": 4678, "imageType": 256
and add it with new **"imageType": 288**

![image](https://user-images.githubusercontent.com/114957153/222952220-3cb8d0a7-a69a-4221-9969-e9f2f6d661fe.png)

**Comment by gedemagt** [comment]
@Koenkk I created a PR for the suggestion by red-island. Please review: https://github.com/Koenkk/zigbee-OTA/pull/274

**Comment by gedemagt** [comment]
Hmm, I tried to download the latest and upload it locally, but I keep getting an "imageType mismatch" error. I downloaded the firmware from here: https://www.danfoss.com/en/products/dhs/smart-heating/smart-heating/danfoss-ally/danfoss-ally-support/#tab-software and the .pdf that comes along clearly states that is should be the new imageType of 288 (0x120). 

Is it z2m or the device that responds check the imageType?

**Comment by hotchkj** [comment]
I'm unconvinced Danfoss have actually set this data up correctly. I'm in the same situation, and the debug logs for the OTA file indicate:

```
getNewImage for '0xa46dd4fffe37f642', image header {"otaUpgradeFileIdentifier":{"type":"Buffer","data":[30,241,238,11]},"otaHeaderVersion":256,"otaHeaderLength":56,"otaHeaderFieldControl":0,"manufacturerCode":4678,"imageType":256,"fileVersion":276,"zigbeeStackVersion":2,"otaHeaderString":"13-12-2022 V.0114.0114\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","totalImageSize":385719}
```
Note the imageType for the file is still listed as `256`, contrary to what their PDF does indeed say.
