### ISSUE TITLE
Question about Philips Hue

### ISSUE THREAD

**Issue by martin82private** [Koenkk/zigbee-OTA#27]
Hi 
the script is not downloading the Philips images , because there is no path in the index.json
or do i something wrong?

br

**Comment by Koenkk** [comment]
Hue images are directly downloaded from the Hue server (e.g. https://github.com/Koenkk/zigbee-OTA/blob/eee9d83be4bfe8d357a5e104b9f7fcf95848e0ec/index.json#L183)
