### ISSUE TITLE
Danfoss Ally - Wrong version shown after update

### ISSUE THREAD

**Issue by red-island** [Koenkk/zigbee-OTA#271]
After FW update strange version is shown.
Seams like the new ota file contains the image for eTRV0100 and eTRV0103.
For eTRV0100 the build date after the update is still the one from version 1.18 from 2021, not the one from 2023 with version 1.20 (guess from the file name).

![image](https://user-images.githubusercontent.com/114957153/222801681-fbbcc280-b83c-4197-859a-2a70936af09d.png)

Before update it looked like this:
![image](https://user-images.githubusercontent.com/114957153/222802464-cfe0ef81-88d1-42f6-90b7-4bf189f61af4.png)

**Comment by MorgothRB** [comment]
I had the same issue when I updated to 1.18. I believe the only full resolution was:
1. Remove the device from Z2M
2. Stop Z2M add-on in HA
3. Factory reset the device
3.a Remove one battery.
3.b Press and hold "o" button.
3.c Insert battery and hold button pressed for about 3 seconds (display will flash all symbols)
4. Start Z2M
5. Start pairing in Z2M and on the device

After that firmware version and date were fine. Didn't try the 1.20 update yet as it seems it doesn't change anything for older models.

**Comment by red-island** [comment]
@MorgothRB thanks for the proposal - can remember I had similar procedure when updating to 1.18 :)

I now tried one (delete from Z2M, reset and join) but it popped up with the same.
Did you achieved to update and show the good version? 
If so we can close this issue and the problem sit in front of my keyboard.

**Comment by red-island** [comment]
Look like the new image contains for eTRV0100 the same 1.18 image, but additionally 1.12 for eTRV0103.
So not sure if the entry in index.json eTRV0100 should not be reversed and point to 1.18 to make it explicit.

![image](https://user-images.githubusercontent.com/114957153/224535129-8c903ce2-5374-43d0-a61f-0fede2e4e076.png)
