### ISSUE TITLE
How to configure Zigbee OTA Firmware Update?

### ISSUE THREAD

**Issue by frfstu** [Koenkk/zigbee-OTA#295]
Hello! Can someone explain in an accessible and understandable form how, where, what and in what settings you need to register / create in order to be able to update devices?
![Снимок экрана от 2023-04-23 15-39-23](https://user-images.githubusercontent.com/87616721/233840341-e37ea8f0-b199-438b-96f5-ef151ce549de.png)
1. There is a wonderfully compiled resource (base) with updates for devices https://github.com/Koenkk/zigbee-OTA/tree/master/images.
2. There are "OTA updates" in the settings menu on the Zigbee2MQTT page.
3. There is an item "OTA index override file name" where you need to specify "Location of override OTA index file".
4. And there is an address in the directory structure openhab-userdata/zigbee/firmware/github.com/Koenkk/zigbee-OTA/raw/master/images/Insta/ also available at /var/lib/openhab/zigbee/firmware/github .com/Koenkk/zigbee-OTA/raw/master/images/Insta/ with the file (as I understand it, with the firmware file for the device ready for installation) ZLL_WS_4f_J_Release_10.03.32.02.zigbee.
Question: What to do next to make the update function work?
![Снимок экрана от 2023-04-23 15-38-20](https://user-images.githubusercontent.com/87616721/233840292-de7d5496-7d88-49f7-9632-da42d5241bd8.png)

**Comment by platini76** [comment]
can be this?
https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

I have the same problem
