### ISSUE TITLE
403 error when updating smart plug

### ISSUE THREAD

**Issue by suchk** [Koenkk/zigbee-OTA#297]
The firmware added in #267 is returning a 403 error. @weihuan1111 do the permissions on the s3 bucket need to be updated?

**Comment by digiblur** [comment]
Same issue here. I checked the URL manually and 403 in the browser too

**Comment by digiblur** [comment]
PR submitted to fix the URLs

https://github.com/Koenkk/zigbee-OTA/pull/298

**Comment by Koenkk** [comment]
thanks @digiblur !
