### ISSUE TITLE
OTA for _TZ3000_6ygjfyll Tuya motion sensor

### ISSUE THREAD

**Issue by KirkKirk** [Koenkk/zigbee-OTA#313]
can we have an OTA for Tuya motion sensor TS0202 by _TZ3000_6ygjfyll ?

Thanks

**Comment by Koenkk** [comment]
Someone needs to retrieve the OTA with the TuYa gateway first: https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html
