### ISSUE TITLE
OTA_lumi.curtain_0.0.0_0034_20200717_1F0A7B.20200717154021.ota is defect

### ISSUE THREAD

**Issue by nukusinji** [Koenkk/zigbee-OTA#32]
I updated OTA ZNCLDJ11LM.
Its model name is lumi.curtain.

OTA update is good. but any zigbee communications is not working after OTA.

LED is not blink by devices when i push reset button.

version info is not change in z2m. because motor can not communication.

**Comment by Koenkk** [comment]
@kirovilya have you tested this FW?

**Comment by kirovilya** [comment]
sorry, but no... I received a set of firmwares "as is" and did not check them :(

**Comment by VOVAiS** [comment]
After updating QBCZ11LM. The device did not start. Having connected your socket to the uart in the console, you can see that the firmware is from another model (not the correct ModelID).
