### ISSUE TITLE
Eurotronic Technology Spirit Zigbee OTA Error

### ISSUE THREAD

**Issue by h-tro** [Koenkk/zigbee-OTA#35]
Hi Koenkk,

I am using a **new** Eurotronic SPZB0001 with firmware 20191014 and Zigbee2mqtt Current version: 1.18.1-2

![EurotronicSpiritZigBee](https://user-images.githubusercontent.com/33256321/111183785-937b4600-85b0-11eb-9fcb-e0b20e3aea6e.JPG)

**and I get the following error:**

_Zigbee2MQTT:error 2021-03-15 15:09:54: Failed to check if update available for 'EurotronicSP-01' (No image available for imageType '65535')_

Can you explain that ?

Thanks
HTro

**Comment by Koenkk** [comment]
It means we have no image for this specific device available, we only have `4364` (https://github.com/Koenkk/zigbee-OTA/blob/0014500fc341c056572ab0694ce63883e082d23c/index.json#L788)

**Comment by h-tro** [comment]
Boost, OFF and Window Open function do not work with firmware firmware 20191014 and a firmware update is not possible.
Do not buy Eurotronic Technology Spirit Zigbee model SPZB0001

**Comment by sorryusernameisalreadytaken** [comment]
> Boost, OFF and Window Open function do not work with firmware firmware 20191014 and a firmware update is not possible.
> Do not buy Eurotronic Technology Spirit Zigbee model SPZB0001

You should write them a email to info@eurotronic.org
Ask for a json url with all ota files and explain a little bit why they should support 3rd party zigbee ota updates (security and fullfill zigbee standards).

**Comment by Hedda** [comment]
It looks like @EUROTRONIC-Technology might be active on GitHub so could try pinging @Witriol and @magicdude4eva

https://github.com/EUROTRONIC-Technology/

https://github.com/EUROTRONIC-Technology/Spirit-ZigBee
