### ISSUE TITLE
Git Hub Web Pages For JSON OTA 

### ISSUE THREAD

**Issue by remylpat** [Koenkk/zigbee-OTA#360]
There is web pages feature on github that could offer to ZigBee2MQTT an easy OTA feature based on the JSON and all the Firmware published here.

More Easy to redirect URL to this JSON Git hub pages than having to host the file locally and do all the process

Would love to have a checkbox on Z2M that point to the complete JSON with firmwares here.

**Comment by Koenkk** [comment]
Maybe I dont understand your request, but this is already done. Z2M directly uses the json file for OTA updates
