### ISSUE TITLE
Tuya OTA-Update for Curtain Module TS130F  _TZ3210_dwytrmda

### ISSUE THREAD

**Issue by LeFlairGoD** [Koenkk/zigbee-OTA#370]
Unfortunately I don't have a Tuya Hub myself to follow this tutorial. 
Does anyone have the same module and can get the OTA updates?
Here are the instructions: https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html
Otherwise I will probably get a hub myself and upload it here.

**Comment by bobmoroshev** [comment]
Did you finally manage to get OTA URL?
