### ISSUE TITLE
OTA for Smart meter Tongou TO-Q-SY1-JZT return version -1

### ISSUE THREAD

**Issue by alexsalvo1** [Koenkk/zigbee-OTA#434]
Hi 

I have this device Tongou TO-Q-SY1-JZT and when I try to update it return that is available version -1.

The device should support OTA based this page: https://www.zigbee2mqtt.io/devices/TO-Q-SY1-JZT.html#tongou-to-q-sy1-jzt

Details of the device:

applicationVersion: 69 
dateCode: '' 
hardwareVersion: 1 
ieeeAddr: '0x385b44fffe1f70ec' 
manufacturerID: 4098 
manufacturerName: _TZ3000_qeuvnohg 
model: TO-Q-SY1-JZT 
networkAddress: 35198 
powerSource: Mains (single phase) 
stackVersion: 0 
type: Router 
zclVersion: 3 

Thanks
Salvo

**Comment by henkiejan1** [comment]
Whatt i know it means there is no OTA file availeble. So you can't update.
