### ISSUE TITLE
Namron Zigbee Touch Termostat 16A 4512752 - New Firmware OTA help

### ISSUE THREAD

**Issue by christian1986** [Koenkk/zigbee-OTA#449]
There is a new firmware for this thermostat. Could anyone assist in adding it?

Changes are the following: 

- Activate the clock function on the thermostat screen. 
- Change the fixed Sleep mode to 5 degrees Celsius as Futurehome utilizes this as a power-saving feature.

Firmware
https://www.elektroimportoren.no/docs/lib/4512752-Firmware-35.zip

**Comment by Koenkk** [comment]
These are not Zigbee OTA files, probably they have to be flashed using a JTAG flasher meaning that I cannot help you further with the OTA part. Contact the manufacturer on how to flash these.
