### ISSUE TITLE
OTA update Impossible Inter roller shutter Legrand 067726A

### ISSUE THREAD

**Issue by XDECO** [Koenkk/zigbee-OTA#457]
Good morning

I am trying to update the FW of my roller shutter switch 067726A unfortunately it is impossible on Home Assistant

I don't know how to force the update

Here is the error I have on the Zigbee2MQTT

Zigbee2MQTT:error 2024-03-14 23:37:54: Update of 'Volet Roulant' failed (OTA: Timeout, device did not request any image blocks)

Can you help me

**Comment by r0m1CH** [comment]
Hi @XDECO 
Did you read this issue: https://github.com/Koenkk/zigbee-OTA/issues/328#issuecomment-1994510285
It worked for me.

**Comment by XDECO** [comment]
Good morning

Yes it works now

THANKS

**Comment by FabianMangold** [comment]
Hi @XDECO,

Would you mind closing this issue if the problem is fixed ?
P.S: We just submitted another PR to solve the version reporting in the latest NLL firmware. (Unfortunately, this problem is still open on Legrand's side).

Cheers
