### ISSUE TITLE
Adding more Develco OTA images

### ISSUE THREAD

**Issue by samuli-as** [Koenkk/zigbee-OTA#459]
I have a couple of Develco devices that seem to be OTA capable hardware/firmware-wise but are not enabled to do so. These are FLSZB-110 ("manufacturerCode":4117,"imageType":768,"fileVersion":197643) 
and 
HMSZB-110 ("manufacturerCode":4117,"imageType":784,"fileVersion":197637)

Does anyone have access to Develco firmware images and could check if there are newer versions for these? If yes, I can do the testing and see how it goes. I don't have access to their support forum and Develco just ignored my messages when I contacted them.

**Comment by RoepLuke** [comment]
Just found these
https://github.com/Develco-Products/frient_upgrade_images

Also advertised in [their FAQs](https://frient.com/faq/) under Product Updates, so seems legit.
