### ISSUE TITLE
New firmware for Gledopto GL-C-006P

### ISSUE THREAD

**Issue by Loic691** [Koenkk/zigbee-OTA#461]
Hi @Koenkk 
I have get a firmware for Gledopto GL-C-006P.
What is the process to upload it on github ? Here or on Z2M repository ?
Is there a way to check the firmware in manual mode before to push it on git ?

Thanks in advance.

**Comment by Koenkk** [comment]
- To upload: https://github.com/Koenkk/zigbee-OTA/blob/master/README.md
- To test locally: https://www.zigbee2mqtt.io/guide/configuration/ota-device-updates.html#ota-index-override-file

**Comment by Loic691** [comment]
Hi thanks
PR is here
https://github.com/Koenkk/zigbee-OTA/pull/462

**Comment by Swampen** [comment]
I'm seing some weird behavior after the update
https://github.com/Koenkk/zigbee2mqtt/issues/21988
