### ISSUE TITLE
Gledopto GL-C-009P

### ISSUE THREAD

**Issue by mrmaximas** [Koenkk/zigbee-OTA#468]
@Koenkk Please disable this update a.s.a.p. because some users have a problems with this fw
https://github.com/Koenkk/zigbee-OTA/issues/463

**Comment by Koenkk** [comment]
Done!

**Comment by mrmaximas** [comment]
@Koenkk how to enable this OTA again BUT for Mini versions only?

**Comment by Koenkk** [comment]
Does the mini have a different `zigbeeModel`?
