### ISSUE TITLE
Moes BRT-100-TRV thermostat got the wrong firmware update from unknown Tuya thermostat.

### ISSUE THREAD

**Issue by vladi1234** [Koenkk/zigbee-OTA#48]
Hello @Koenkk is a big problem.
Look here:
https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-906243509

**Comment by wizu** [comment]
@Koenkk is there a way to update HY-368 with this temporary fix? Or should I wait for to final fix?
