### ISSUE TITLE
GL-C-006P(normal) received GL-C-006P(mini) OTA from Z2M

### ISSUE THREAD

**Issue by marce14-git** [Koenkk/zigbee-OTA#483]
GL-C-006P (normal version) received the OTA for the MINI Version an is now unusable - all commands are received but light does not turn on etc.

GL-C-006P (normal) has now the GL-C-006P (mini) Firmware = Build Date: 20240227 Version: 20451203.

Manual OTA Update with the right firmware: `"url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Gledopto/GL-C-006P_10576802_20240412.ota"` just says no firmware update available

see #https://github.com/Koenkk/zigbee2mqtt/issues/22287

[
![image](https://github.com/Koenkk/zigbee-OTA/assets/92689239/da786753-ccd3-424d-97a8-4ed328d2fda2)
](url)
[
![image](https://github.com/Koenkk/zigbee-OTA/assets/92689239/737bd675-36e3-45c0-8f7e-af0d8e3a0195)
](url)

**Comment by mariustt** [comment]
I have exactly the same problem. Additionally, I received the latest OTA version of GL-C-006P (not the mini) from the supplier - https://drive.google.com/file/d/1hA7h_qHQbrTFgNz0aJVS8HNuxzao8MZa

**Comment by marce14-git** [comment]
the root of the problem is that GL-C-006P and GL-C-006P(mini) are not distinguished as seperate entities in Z2M and a new FW for either one of the devices shows up for both.

**Comment by marce14-git** [comment]
> I have exactly the same problem. Additionally, I received the latest OTA version of GL-C-006P (not the mini) from the supplier - [GL-C-006P_V20451203_KEY_20240227.zip](https://github.com/Koenkk/zigbee-OTA/files/15125580/GL-C-006P_V20451203_KEY_20240227.zip)

your firmware did not work because it was the same Version Number than the one the device had - i was able to resolve my problem by emailing Gledopto and getting a new FW see #22287

**Comment by mariustt** [comment]
Thank you for the information, @marce14-git !
I have tried your OTA, the update was successful, but the lights still do not turn on/off. Didn't you do an additional factory reset?

I just want to point out that your OTA is not the latest. I have 9 led drivers. 6 of them I bought at the end of 2022, 3 at the end of 2023. Buy the 2022 version - 10651203, and buy the 2023 version - 20351203.

![image](https://github.com/Koenkk/zigbee-OTA/assets/122723994/07861ac2-2edc-4934-9fc8-1afe185c2781)

**Comment by marce14-git** [comment]
> Thank you for the information, @marce14-git ! I have tried your OTA, the update was successful, but the lights still do not turn on/off. Didn't you do an additional factory reset?
> 
> I just want to point out that your OTA is not the latest. I have 9 led drivers. 6 of them I bought at the end of 2022, 3 at the end of 2023. Buy the 2022 version - 10651203, and buy the 2023 version - 20351203.
> 
> ![image](https://private-user-images.githubusercontent.com/122723994/326257045-07861ac2-2edc-4934-9fc8-1afe185c2781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTA4MDQsIm5iZiI6MTcxNDMxMDUwNCwicGF0aCI6Ii8xMjI3MjM5OTQvMzI2MjU3MDQ1LTA3ODYxYWMyLTJlZGMtNDkzNC05ZmM4LTFhZmUxODVjMjc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxMzIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTYzMDRlMzc3OWRlNTI3ZTM4YTA1YzJjNWZhNWFmNWU3NDk3YTRlZmQxNjRiOGYzMmM2NzYzOGNhZmU3ZjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-VnedCfI5j4Jf6qdHuYUoBLZxAB_PeFhS43i00wY8t0)

No i just did the steps as mentioned in the other Post and everything worked on the spot. Sorry to hear that it didnt for you

**Comment by mariustt** [comment]
@marce14-git the problem was solved with your OTA - thank you! I updated my PR by changing my OTA to yours (https://github.com/Koenkk/zigbee-OTA/pull/486).

**Comment by mariustt** [comment]
@Koenkk I think we can mark this one as closed because it is resolved with this PR - https://github.com/Koenkk/zigbee-OTA/pull/486
