### ISSUE TITLE
Cannot update Bticino shutter K4027C because firmware is newer then latest firmware online

### ISSUE THREAD

**Issue by Crystian182** [Koenkk/zigbee-OTA#526]
Hello!

## Issue
I'm not able to update the firmware for my shutter switch Bticino K4027C anymore because `Firmware on '0x000474000148043a' ( Shutter SW with level control) is newer than latest firmware online.`

<img width="393" alt="Screenshot 2024-07-15 at 20 07 23" src="https://github.com/user-attachments/assets/f0aa2fa5-284d-49b5-8a20-d134a82024fe">

## Details

Current firmware is 002c, version 2900483
<img width="1197" alt="Screenshot 2024-07-15 at 20 07 45" src="https://github.com/user-attachments/assets/f12aca26-ec66-4919-bdab-973a69b7975a">
<img width="368" alt="Screenshot 2024-07-15 at 20 08 11" src="https://github.com/user-attachments/assets/8d7115f5-2222-488c-8be2-4504debe8f51">

And I used to successfully do update other devices in the past.
E.g. the following K4027C device came with the 002c fw but I easily managed to update it to 003c, version 3950079
<img width="1197" alt="Screenshot 2024-07-15 at 20 07 53" src="https://github.com/user-attachments/assets/7ee7582c-4ada-4c0a-8e10-8354b8314abc">
<img width="368" alt="Screenshot 2024-07-15 at 20 08 21" src="https://github.com/user-attachments/assets/b75bdc85-640e-44f6-b571-1c3725fdf999">

---

The new fw introduces some behaviour changes (i.e. the way I can stop the shutter) which are very useful, so it would be nice to have the latest version.

I can also contribute if i get some hints :)

Thanks!

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee-OTA/issues/527
