### ISSUE TITLE
Tuya Firmware - origin?

### ISSUE THREAD

**Issue by rusitschka** [Koenkk/zigbee-OTA#53]
I contacted Tuya about adding a feature to their Firmware of TRV. Tuya service told me they are not responsible but the "device manufacturer". When asking who that is they said to ask the seller. Seems like they don't want to tell. Since this repo contains the firmware for that TRV: Where did you get it from? Do you know who to contact for feature requests in that firmware?

**Comment by CWempe** [comment]
I am interested in this, too.

And I would like to see the changelog of the OTA-Update (Tuya TVR).
Maybe we find it there, too.

**Comment by CWempe** [comment]
I think I just found the answer to both our questions:

https://github.com/Koenkk/zigbee-OTA/pull/43#issuecomment-864113224

1. The firmware is provided from users like us, who somehow dumped the firmware form an app.
2. There is no changelog.

But I understand Tuya does not/cannot tell the manufacturer.
Tuya is a company that creates the software and cloud infrastructure for MANY different manufacturers who buy/license these services from Tuy.
We are not the customers of Tuya, but the manufacturer is the customer of Tuya.

**Comment by fabicodes** [comment]
> Where did you get it from? 
I guess I was the first one that published a link to the firmware in this [comment](https://github.com/Koenkk/zigbee2mqtt/issues/3821#issuecomment-702825657), got it while I was having the original Gateway. Used MITMProxy to log the communication between the App and the Tuya Backend Server.
> Do you know who to contact for feature requests in that firmware?
No
