### ISSUE TITLE
Request to add firmware eurotronic spirit zigbee

### ISSUE THREAD

**Issue by Lupog** [Koenkk/zigbee-OTA#595]
Hi, I'm asking you if it would be possible to add this ota file, thank you very much!!

https://github.com/EUROTRONIC-Technology/Spirit-ZigBee/releases

**Comment by Koenkk** [comment]
It's already there: https://github.com/Koenkk/zigbee-OTA/blob/62c4f38c01b984c5a57e3c5e966b484022c7d96f/index.json#L1421
