### ISSUE TITLE
The issue with Lumi upgrades after updating zigbee-OTA.

### ISSUE THREAD

**Issue by z-x-f** [Koenkk/zigbee-OTA#612]
Currently, in index.json, there are two OTA files for the same hardware. How are they handled? After I added a new OTA file, it cannot detect the upgrade.

**Comment by Koenkk** [comment]
It will pick the first matching one, but I think it would be good to remove the duplicate.

**Comment by z-x-f** [comment]
After a zigbee-OTA update, is it expected that the new firmware added will automatically move the old firmware to the images1 folder?

**Comment by Koenkk** [comment]
Yes! Those are used for downgrades

**Comment by z-x-f** [comment]
Ah, what did I do wrong when I submitted the PR? Was it because I didn't attach the `modelID`? I saw that the old firmware was not automatically moved to `images1` and the `index.json` did not delete the old OTA upgrade information.
