### ISSUE TITLE
updateall/add script removes custom Tuya manufacturerNames

### ISSUE THREAD

**Issue by TheJulianJES** [Koenkk/zigbee-OTA#62]
https://github.com/Koenkk/zigbee-OTA/pull/50 added custom ``manufacturerNames`` to some Tuya devices:
https://github.com/Koenkk/zigbee-OTA/blob/db0ead70a4370d7f5b8dfa605c5b85af8068b9fd/index.json#L753-L757

Running ``node scripts/updateall.js`` (which runs ``add.js`` on each file) seems to remove these custom ``manufacturerNames``.

**Comment by Koenkk** [comment]
Fixed, thanks for reporting.
