### ISSUE TITLE
Hue OTA files

### ISSUE THREAD

**Issue by mkaay** [Koenkk/zigbee-OTA#7]
I spent the last few evenings reverse engineering the communication between the hue bridge and the Philips servers and now i can query the device portal endpoints.
You have to know the manufacturer id and image id to query the firmware update service.
Through some searching and experimenting I managed to get some valid combinations you can find [here](https://gist.github.com/mkaay/6f19594fa77792f107e8b5e3c438d9f2).
I'm thinking of setting up a site to make automation easier, so if you have any suggestions for the output format or missing image ids please share.

**Comment by Koenkk** [comment]
Great! Are you planning to deliver this to https://github.com/Koenkk/zigbee-OTA/blob/master/index.json ?

**Comment by mkaay** [comment]
Yes, i'm just about to finish writing a script to update the records.
Is it okay if I use the original url, or do you want the files mirrored in this repo?
