### ISSUE TITLE
no modelId 

### ISSUE THREAD

**Issue by zvldz** [Koenkk/zigbee-OTA#91]
Is it right that there is no `modelId` ?
https://github.com/Koenkk/zigbee-OTA/blob/master/index.json#L1320-L1346

**Comment by Koenkk** [comment]
It would be better to have a model id, this prevent loading the firmware on other Xiaomi devices in case they use the same image type, could you make a pr for this?

**Comment by zvldz** [comment]
Yes, I will, a little later.
Thanks

**Comment by zvldz** [comment]
added to https://github.com/Koenkk/zigbee-OTA/pull/90/

**Comment by Koenkk** [comment]
perfect!
